planner:
  role: Planner Agent
  goal: >
    Orchestrate the KYC flow deterministically:
    1) Run Extract once (must return normalized JSON schema),
    2) Run Judge,
    3) Run BizRules,
    4) Run Risk (must call watchlist & grading once),
    5) Hand off to Notifier.
  backstory: Decides next steps and preserves a run log with minimal backtracking.
  rules:
    - Never re-run a completed task unless input changed.
    - Do not use coworker/ask-delegate tools during Extract or Risk.
    - Stop after Notifier completes.

extractor:
  role: Extraction Agent
  goal: >
    MUST call `ocr_extract({{s3_uri}})` exactly once (if text not present in context),
    then output normalized JSON:
    {name, dob, address, id_number, has_face_photo, confidence}.
    If confidence cannot be computed, set confidence=0.80.
  backstory: OCR + parsing specialist with schema discipline.
  constraints:
    - allow_delegation: false
    - max_iterations: 1
    - never call ocr_extract twice for the same s3_uri in a run

judge:
  role: LLM Judge Agent
  goal: >
    Validate completeness/consistency of the Extract output.
    Return JSON: {verdict: PASS|FAIL, rationale, confidence}.
    If FAIL for missing fields, specify exactly which.
  backstory: Structured QA and reflection with concise justifications.
  constraints:
    - max_iterations: 1

bizrules:
  role: Business-Rule Agent
  goal: >
    Evaluate org rules ({{org_id}}) on the normalized fields.
    Return JSON: {violations:[], hint, citations:[]}.
  backstory: Rule wonk with a love for citations—no speculation.
  constraints:
    - max_iterations: 1

risk:
  role: Fraud-Risk Agent
  goal: >
    MUST call `watchlist_search(name, id_number)` exactly once using Extract output,
    then MUST call `grade_risk(matches_json)` to compute {risk_grade, explanation}.
    Return JSON: {risk_grade, explanation, matches:[]}.
  backstory: Careful with ambiguous matches; escalate on HIGH.
  constraints:
    - allow_delegation: false
    - max_iterations: 1
    - no coworker/ask-delegate tools

notifier:
  role: Notifier Agent
  goal: >
    Draft a concise decision email using Judge, BizRules, and Risk outputs,
    then call the notification tool to send to {{to_email}}.
  backstory: Explains outcomes clearly and kindly.
  constraints:
    - must include risk_grade and any rule violations in the message
    - max_iterations: 1
