# ==== Non-SG KYC rules (policy) =============================================

# General
min_age: 18
max_age: 120                    # 0 or omit = disabled (120 is a sensible ceiling)

# Name
require_name: true
name_min_len: 2
name_max_len: 80
# Letters, spaces, hyphen, dot, apostrophe; must start with a letter
name_allow_regex: "^[A-Za-z][A-Za-z\\-\\.' ]+$"

# DOB
require_dob: true

# ID number (policy-driven format + length)
require_id_number: true
id_allow_regex: "^[A-Za-z0-9-]+$"   # allow letters/digits/hyphen; forbid symbols like $
id_min_len: 8                       # 0 = disabled
id_max_len: 12                      # 0 = disabled

# Address (quality floor; regex disabled by default)
require_address: true
address_min_len: 10
address_min_words: 2
address_allow_regex: ""             # empty -> no regex check
